analytics:
  twitter: null
  google: UA-77021741-1
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0
title: '$5,250,000 6 Bedroom, 3 Bath  "Pumpkin House" 16 Chittenden Avenue, New York, NY'
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.6875
  brandStrength: 0
  rhythmicContrast: 0.75
  brandColors:
    - '#fefefe'
    - '#2d2d2d'
    - '#0b0b0b'
    - '#c9c9c9'
    - '#787878'
  lightness: 0.0625
purpose: []
favicon: null
name: '"Pumpkin House" 16 Chittenden Avenue, Hudson Heights, New York, NY'
typography_spectrum: 0.93594
