name: '"Pumpkin House" 16 Chittenden Avenue, Hudson Heights, New York, NY'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.93594
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: '$5,250,000 6 Bedroom, 3 Bath  "Pumpkin House" 16 Chittenden Avenue, New York, NY'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77021741-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#fefefe'
    - '#beae9d'
    - '#8f755c'
    - '#3b3b47'
  brandStrength: 0.75
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
