name: '"Pumpkin House" 16 Chittenden Avenue, Hudson Heights, New York, NY'
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: '$5,250,000 6 Bedroom, 3 Bath  "Pumpkin House" 16 Chittenden Avenue, New York, NY'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77021741-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2d2d2d'
    - '#0b0b0b'
    - '#c9c9c9'
    - '#787878'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
