name: Pumpkin House
favicon: null
layout_spectrum: 0.93149
typography_spectrum: 0.9653
title: 'For Sale: $5,250,000  16 Chittenden Avenue, New York, NY'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77021741-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2d2d2d'
    - '#0b0b0b'
    - '#c9c9c9'
    - '#787878'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
