name: '"Pumpkin House" 16 Chittenden Avenue, Hudson Heights, New York, NY'
favicon: null
layout_spectrum: 0.97598
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ' Historic  "Pumpkin House" for Sale, $5,250,000  16 Chittenden Avenue, New York, NY'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77021741-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bbbbbb'
    - '#d9d9d9'
    - '#1e1e1e'
    - '#555555'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
